/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamingIndexRouteImport } from './routes/streaming/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as ApiChatJsonlRouteImport } from './routes/api/chat-jsonl'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingIndexRoute = StreamingIndexRouteImport.update({
  id: '/streaming/',
  path: '/streaming/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatJsonlRoute = ApiChatJsonlRouteImport.update({
  id: '/api/chat-jsonl',
  path: '/api/chat-jsonl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-jsonl': typeof ApiChatJsonlRoute
  '/health/': typeof HealthIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/streaming/': typeof StreamingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-jsonl': typeof ApiChatJsonlRoute
  '/health': typeof HealthIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/streaming': typeof StreamingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-jsonl': typeof ApiChatJsonlRoute
  '/health/': typeof HealthIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/streaming/': typeof StreamingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat-jsonl'
    | '/health/'
    | '/questions/'
    | '/streaming/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat-jsonl'
    | '/health'
    | '/questions'
    | '/streaming'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat-jsonl'
    | '/health/'
    | '/questions/'
    | '/streaming/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatJsonlRoute: typeof ApiChatJsonlRoute
  HealthIndexRoute: typeof HealthIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  StreamingIndexRoute: typeof StreamingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming/': {
      id: '/streaming/'
      path: '/streaming'
      fullPath: '/streaming/'
      preLoaderRoute: typeof StreamingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-jsonl': {
      id: '/api/chat-jsonl'
      path: '/api/chat-jsonl'
      fullPath: '/api/chat-jsonl'
      preLoaderRoute: typeof ApiChatJsonlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatJsonlRoute: ApiChatJsonlRoute,
  HealthIndexRoute: HealthIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  StreamingIndexRoute: StreamingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
